version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_ignite    
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - ignite
    
  app:
    build: 
       context: .
    container_name: ignite_rentalx
    ports:
     - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    networks:
      - ignite
    
volumes:
  pgdata:
    driver: local

networks:
  ignite:
    driver: bridge